#!/usr/bin/env python3
"""
add_stereo_change.py
=====================
Adds `stereo_change` (fact) to an existing master parquet, computed from the
`mapped_rxn` column already present -- NO new RXNMapper call, pure RDKit,
CPU-only, runs on the login node. Meant to run AFTER add_reaction_center.py,
on the same file.

DEFINITION: for every atom (by map number) that is a stereocenter on at least
one side of the reaction, classify what happened to it:

  created     - not a stereocenter in reactants, IS one in the product
                (a new stereocenter was generated by the reaction)
  destroyed   - was a stereocenter in reactants, is NOT one in the product
                (planarization, e.g. oxidation to a ketone)
  resolved    - stereocenter was UNASSIGNED ('?') in reactants, DEFINED (R/S)
                in the product -- e.g. racemic resolution, or simply better
                specified stereochemistry recorded on the product side.
                CONFIRMED AS A REAL, NON-RARE CASE: this is exactly what most
                of the empty-reaction_center rows in the ORD-derived corpus
                turned out to be (chiral resolutions with no bond change at
                all) -- see add_reaction_center.py's documented finding.
  unresolved  - the reverse of 'resolved': defined in reactants, unassigned
                in product (rare, worth flagging -- may indicate a curation
                or mapping issue, not a真 chemical event)
  inverted    - defined stereocenter on BOTH sides, R<->S flip (true
                stereoinversion, e.g. SN2 at a stereocenter)
  retained    - same defined configuration on both sides (stereochemistry
                correctly preserved through the reaction)
  unclear     - edge case (e.g. unassigned on both sides -- no information
                either way)

WHY THIS MATTERS FOR StereoRetro: this is the fact-level substrate for the
Stereo Retention Rate metric. Rather than measuring retention only at the
model-output level, it can now be computed directly and consistently from the
master for ANY subset of reactions, across all four sources, using one
definition.

VALIDATED before being applied at scale:
  1. On a real corpus row (an ORD reaction with an empty reaction_center that
     turned out to be a stereocenter resolution, exactly as characterized in
     add_reaction_center.py) -- correctly returns {atom: 'resolved'}.
  2. On a constructed SN2 inversion at a genuine 4-distinct-substituent
     stereocenter (F/Cl/Br/H) -- correctly returns {atom: 'inverted'}. An
     earlier draft test used a degenerate SMILES with two identical methyl
     substituents, which RDKit correctly does NOT recognize as a stereocenter
     at all -- that was a flawed test construction, not a script bug, caught
     by checking RDKit's own chiral-center detection before trusting the
     result.

Output: `stereo_change` column, stored as a pipe-joined "mapnum:category"
string list for parquet compatibility (consistent with how `reaction_center`
is stored). Rows with no valid mapping or no stereocenters at all get an empty
string (not None) -- an explicit, checkable "no stereo signal here" fact,
distinct from "couldn't be parsed" (None).
"""
import argparse
import time
from collections import Counter

import pandas as pd
from rdkit import Chem
from rdkit import RDLogger
RDLogger.DisableLog("rdApp.*")


def log(m):
    print(f"[{time.strftime('%H:%M:%S')}] {m}", flush=True)


def get_stereocenters_by_map(mol):
    """map_num -> 'R' / 'S' / '?' (unassigned) for every stereocenter."""
    centers = Chem.FindMolChiralCenters(mol, includeUnassigned=True,
                                        useLegacyImplementation=False)
    result = {}
    for atom_idx, chirality in centers:
        atom = mol.GetAtomWithIdx(atom_idx)
        mnum = atom.GetAtomMapNum()
        if mnum > 0:
            result[mnum] = chirality
    return result


def stereo_change(mapped_rxn):
    """dict {map_num: category}. None if unparseable."""
    if not isinstance(mapped_rxn, str) or ">>" not in mapped_rxn:
        return None
    lhs, rhs = mapped_rxn.split(">>")
    left_mol = Chem.MolFromSmiles(lhs)
    right_mol = Chem.MolFromSmiles(rhs)
    if left_mol is None or right_mol is None:
        return None

    left_centers = get_stereocenters_by_map(left_mol)
    right_centers = get_stereocenters_by_map(right_mol)
    all_maps = set(left_centers) | set(right_centers)

    result = {}
    for mnum in all_maps:
        l = left_centers.get(mnum)
        r = right_centers.get(mnum)
        if l is None and r is not None:
            result[mnum] = "created"
        elif l is not None and r is None:
            result[mnum] = "destroyed"
        elif l == "?" and r not in (None, "?"):
            result[mnum] = "resolved"
        elif l not in (None, "?") and r == "?":
            result[mnum] = "unresolved"
        elif l is not None and r is not None and l != r and l != "?" and r != "?":
            result[mnum] = "inverted"
        elif l == r:
            result[mnum] = "retained"
        else:
            result[mnum] = "unclear"
    return result


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="infile", required=True)
    ap.add_argument("--out", dest="outfile", required=True)
    args = ap.parse_args()

    log(f"loading {args.infile}")
    df = pd.read_parquet(args.infile)
    log(f"{len(df):,} rows loaded")

    if "mapped_rxn" not in df.columns:
        raise SystemExit("No 'mapped_rxn' column found -- run after the mapping step.")

    log("computing stereo_change (pure RDKit, CPU) ...")
    t0 = time.time()
    raw = df["mapped_rxn"].apply(stereo_change)
    log(f"done in {(time.time()-t0)/60:.1f} min")

    n_valid = raw.notna().sum()
    log(f"stereo_change computed for {n_valid:,}/{len(df):,} rows "
       f"({100*n_valid/len(df):.1f}%)")

    # category-level summary across the whole corpus
    counter = Counter()
    for d in raw.dropna():
        for cat in d.values():
            counter[cat] += 1
    log("category breakdown across all stereocenters found:")
    for cat, n in counter.most_common():
        log(f"  {cat:12s} {n:>10,}")

    n_any_change = raw.apply(
        lambda d: isinstance(d, dict) and any(
            v not in ("retained",) for v in d.values())
    ).sum()
    n_has_stereocenter = raw.apply(lambda d: isinstance(d, dict) and len(d) > 0).sum()
    log(f"rows with >=1 stereocenter on either side: {n_has_stereocenter:,}")
    log(f"rows where >=1 stereocenter changed status (not just 'retained'): "
       f"{n_any_change:,}")

    df["stereo_change"] = raw.apply(
        lambda d: "|".join(f"{k}:{v}" for k, v in d.items())
        if isinstance(d, dict) else None
    )

    df.to_parquet(args.outfile, index=False)
    log(f"wrote {args.outfile}")


if __name__ == "__main__":
    main()
